### ISSUE TITLE
Preparar os dados sinteticos para a predicao

### ISSUE THREAD

**Issue by marcelovmaciel** [leonardoluzserrano/ProjetoPRF#17]
- Definir as datas
- Definir se sao feriados pre ou pos
- Setar brs para 232 e 104
- Da data derivar  'mes', 'dia_semana',  e dropar a data
- Setar os bins de cada br
-  Replicar os datasets para diferentes condicoes meterologicas e concatenar
- Fazer o mesmo para fase do dia
- Pensar uma estrategia para o tracado_via

**Comment by marcelovmaciel** [comment]
@leonardoluzserrano

**Comment by leonardoluzserrano** [comment]
data ja setado, br ja setada, bin ja setado

**Comment by leonardoluzserrano** [comment]
Falta a coluna de feriado e o tracado_via

**Comment by leonardoluzserrano** [comment]
feriados pre e pos foi implementado. Falta tracado_via

**Comment by marcelovmaciel** [comment]
noi abre nova issue pra isso
