### ISSUE TITLE
Reorganizar codigo 

### ISSUE THREAD

**Issue by marcelovmaciel** [leonardoluzserrano/ProjetoPRF#19]
- Separar definicoes de proc calls

**Comment by leonardoluzserrano** [comment]
- Atualizar os nomes de funções e de variáveis para que sejam mais representativos
- Modularizar o código, um arquivo pra modelos, um pra preprocessamento, um pra as funções
- Revisar e remover scripts desnecessários. Deixar o projeto mais enxuto.

**Comment by leonardoluzserrano** [comment]
- Limpar gitignore (Rodrigo parece ter usado um template. Too bloated.)

**Comment by marcelovmaciel** [comment]
amanha de manha derrubamos isso; ja separei a limpeza do preprocessamento

**Comment by hugoabreu1002** [comment]
sugiro:
- melhorar o Readme (explicando os diretórios onde as bases vão ficar e de onde elas vêm)
- main.py
- cleaning.py (deixando preprocessamento junto aqui também)
- rank.py

main, chamaria tudo, que seria funções descritas nós packages cleaning e rank.

**Comment by marcelovmaciel** [comment]
- agora so falta a agregacao. farei

**Comment by marcelovmaciel** [comment]
foi derrubado praticamente. so deletar umas coisas. a agregacao fica de cada um na real
