### ISSUE TITLE
Km estranho - Acima de 2000 km e abaixo de 0

### ISSUE THREAD

**Issue by michaellopes16** [leonardoluzserrano/ProjetoPRF#23]
Linha 15962: km = -192.6  BR: 232
Linha 48932: km = -143.7 BR: 232

----------
Linha : 19631: km= 2759.0 BR: 232
Linha : 19632: km= 2759.0 BR: 232
Linha : 19633: km= 2759.0 BR: 232

**Comment by marcelovmaciel** [comment]
resolvido em https://github.com/leonardoluzserrano/ProjetoPRF/commit/1311e1e6c33ed67ad25c8b8ff3f9ae2134097c33
