### ISSUE TITLE
Fluxograma e limpeza do diretório

### ISSUE THREAD

**Issue by hugoabreu1002** [leonardoluzserrano/ProjetoPRF#24]
pode parecer "frescura" mas só de cleaning/preprocessamento tem uns 6 arquivo entre ipynb e .py.

ajudaria tirar uns minutinhos quando der para deixar apenas o que estiver no fluxograma.

Além disto, descrever brevemente o fluxograma e colocar o link para a pasta '/data' no readme. 
Ainda não entendi se a /data é gerada automáticamente ou é só baixando.

PS: eu queria ajudar nos outros issues mas eu ainda não entendi o fluxo do código.

**Comment by marcelovmaciel** [comment]
fluxograma vira, tirei alguns arquivos n todos pq tem coisa que serve pra abordagem que ja tava em curso

**Comment by marcelovmaciel** [comment]
- mover os mds para um diretorio deles

**Comment by marcelovmaciel** [comment]
ver https://github.com/leonardoluzserrano/ProjetoPRF/tree/master/descriptions . Rolar algum problema reabre a issue.
